name: CI/CD Pipeline for Maven Operations
on:
  pull_request:
    types: opened
    branches:
      - master
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - uses: actions/checkout@v4
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # cache: Maven
      - name: Build with Maven
        run: mvn clean install
