name: CI/CD Pipeline for Maven Operations
on:
  pull_request:
    types: opened
    branches:
      - master
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
