name: CI/CD Pipeline for Maven Operations
on:
  pull_request:
    types: opened
    branches:
      - master
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "Starting Maven Clean"
      - uses: actions/checkout@v4
      - name: Set Up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
          # cache: Maven
      - name: Clean with Maven
        run: mvn clean
  build:
    needs: clean
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "Starting Maven Test"
      - uses: actions/checkout@v4
      - name: Set Up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
            # cache: Maven
      - name: Install with Maven
        run: mvn install
       
